* Elias Nogueira 
* Jo√£o Pedro Nunes
* Derek

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
from mlxtend.frequent_patterns import apriori, association_rules


df1 = pd.read_csv('/content/Groceries_dataset - Groceries_dataset.csv')
df2 = pd.read_csv('/content/Grocery Products Purchase - Grocery Products Purchase.csv')

df1.head()

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk

In [ ]:
df1.describe()

       Member_number
count   38765.000000
mean     3003.641868
std      1153.611031
min      1000.000000
25%      2002.000000
50%      3005.000000
75%      4007.000000
max      5000.000000

In [ ]:
df2.head()

          Product 1            Product 2  ... Product 31 Product 32
0      citrus fruit  semi-finished bread  ...        NaN        NaN
1    tropical fruit               yogurt  ...        NaN        NaN
2        whole milk                  NaN  ...        NaN        NaN
3         pip fruit               yogurt  ...        NaN        NaN
4  other vegetables           whole milk  ...        NaN        NaN

[5 rows x 32 columns]

In [ ]:
df2.describe()

       Product 1   Product 2  ...        Product 31 Product 32
count       9835        7676  ...                 1          1
unique       158         151  ...                 1          1
top      sausage  whole milk  ...  hygiene articles    candles
freq         825         654  ...                 1          1

[4 rows x 32 columns]

In [ ]:
df1['itemDescription'].unique()

array(['tropical fruit', 'whole milk', 'pip fruit', 'other vegetables',
       'rolls/buns', 'pot plants', 'citrus fruit', 'beef', 'frankfurter',
       'chicken', 'butter', 'fruit/vegetable juice',
       'packaged fruit/vegetables', 'chocolate', 'specialty bar',
       'butter milk', 'bottled water', 'yogurt', 'sausage', 'brown bread',
       'hamburger meat', 'root vegetables', 'pork', 'pastry',
       'canned beer', 'berries', 'coffee', 'misc. beverages', 'ham',
       'turkey', 'curd cheese', 'red/blush wine',
       'frozen potato products', 'flour', 'sugar', 'frozen meals',
       'herbs', 'soda', 'detergent', 'grapes', 'processed cheese', 'fish',
       'sparkling wine', 'newspapers', 'curd', 'pasta', 'popcorn',
       'finished products', 'beverages', 'bottled beer', 'dessert',
       'dog food', 'specialty chocolate', 'condensed milk', 'cleaner',
       'white wine', 'meat', 'ice cream', 'hard cheese', 'cream cheese',
       'liquor', 'pickled vegetables', 'liquor (appetizer)', 'UHT-milk',
       'candy', 'onions', 'hair spray', 'photo/film', 'domestic eggs',
       'margarine', 'shopping bags', 'salt', 'oil', 'whipped/sour cream',
       'frozen vegetables', 'sliced cheese', 'dish cleaner',
       'baking powder', 'specialty cheese', 'salty snack',
       'Instant food products', 'pet care', 'white bread',
       'female sanitary products', 'cling film/bags', 'soap',
       'frozen chicken', 'house keeping products', 'spread cheese',
       'decalcifier', 'frozen dessert', 'vinegar', 'nuts/prunes',
       'potato products', 'frozen fish', 'hygiene articles',
       'artif. sweetener', 'light bulbs', 'canned vegetables',
       'chewing gum', 'canned fish', 'cookware', 'semi-finished bread',
       'cat food', 'bathroom cleaner', 'prosecco', 'liver loaf',
       'zwieback', 'canned fruit', 'frozen fruits', 'brandy',
       'baby cosmetics', 'spices', 'napkins', 'waffles', 'sauces', 'rum',
       'chocolate marshmallow', 'long life bakery product', 'bags',
       'sweet spreads', 'soups', 'mustard', 'specialty fat',
       'instant coffee', 'snack products', 'organic sausage',
       'soft cheese', 'mayonnaise', 'dental care', 'roll products',
       'kitchen towels', 'flower soil/fertilizer', 'cereals',
       'meat spreads', 'dishes', 'male cosmetics', 'candles', 'whisky',
       'tidbits', 'cooking chocolate', 'seasonal products', 'liqueur',
       'abrasive cleaner', 'syrup', 'ketchup', 'cream', 'skin care',
       'rubbing alcohol', 'nut snack', 'cocoa drinks', 'softener',
       'organic products', 'cake bar', 'honey', 'jam', 'kitchen utensil',
       'flower (seeds)', 'rice', 'tea', 'salad dressing',
       'specialty vegetables', 'pudding powder', 'ready soups',
       'make up remover', 'toilet cleaner', 'preservation products'],
      dtype=object)

In [ ]:
lista_compras = df2.values.tolist()
compras = []

for j in lista_compras:
  compras.append([i for i in j if str(i) != "nan"])

compras[0]

['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups']

In [ ]:
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_ary = te.fit(compras).transform(compras)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

      Instant food products  UHT-milk  ...  yogurt  zwieback
0                     False     False  ...   False     False
1                     False     False  ...    True     False
2                     False     False  ...   False     False
3                     False     False  ...    True     False
4                     False     False  ...   False     False
...                     ...       ...  ...     ...       ...
9830                  False     False  ...   False     False
9831                  False     False  ...   False     False
9832                  False     False  ...    True     False
9833                  False     False  ...   False     False
9834                  False     False  ...   False     False

[9835 rows x 169 columns]

In [ ]:
from mlxtend.frequent_patterns import apriori, association_rules

frequent_itemsets = apriori(df, min_support=0.02, use_colnames=True)

frequent_itemsets['support'].describe()

count    122.000000
mean       0.045115
std        0.037346
min        0.020031
25%        0.024530
50%        0.030452
75%        0.051678
max        0.255516
Name: support, dtype: float64

In [ ]:
frequent_itemsets.sort_values(by='support',ascending=False).head(10)

     support            itemsets
57  0.255516        (whole milk)
39  0.193493  (other vegetables)
43  0.183935        (rolls/buns)
49  0.174377              (soda)
58  0.139502            (yogurt)
5   0.110524     (bottled water)
44  0.108998   (root vegetables)
53  0.104931    (tropical fruit)
47  0.098526     (shopping bags)
46  0.093950           (sausage)

In [ ]:
rules =  association_rules(frequent_itemsets, metric="confidence", min_threshold=0.4)
rules

                            antecedents  ... conviction
0                                (beef)  ...   1.251315
1                              (butter)  ...   1.480817
2                                (curd)  ...   1.461085
3                       (domestic eggs)  ...   1.412030
4                   (frozen vegetables)  ...   1.294636
5                           (margarine)  ...   1.268706
6                     (root vegetables)  ...   1.426693
7                  (whipped/sour cream)  ...   1.350565
8                     (root vegetables)  ...   1.350401
9                      (tropical fruit)  ...   1.247252
10                 (whipped/sour cream)  ...   1.352735
11                             (yogurt)  ...   1.244132
12  (other vegetables, root vegetables)  ...   1.457687
13        (whole milk, root vegetables)  ...   1.533320
14           (other vegetables, yogurt)  ...   1.528340

[15 rows x 9 columns]

In [ ]:
rules.describe()

       antecedent support  consequent support  ...   leverage  conviction
count           15.000000           15.000000  ...  15.000000   15.000000
max              0.139502            0.255516  ...   0.026291    1.533320
75%              0.088307            0.255516  ...   0.015246    1.459386
mean             0.071784            0.243111  ...   0.014202    1.377314
50%              0.058566            0.255516  ...   0.013719    1.352735
25%              0.050686            0.255516  ...   0.011125    1.281671
min              0.043416            0.193493  ...   0.007845    1.244132
std              0.029480            0.025680  ...   0.005059    0.102185

[8 rows x 7 columns]